// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBU8YU6f9RduJrgkvKbd1buR4zl_as9HI',
    appId: '1:245885129906:android:acfd2a00b6d5c66d8b65ab',
    messagingSenderId: '245885129906',
    projectId: 'saadp-88043',
    storageBucket: 'saadp-88043.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqhCjlpYaozaD-1vCo8mzrSHsqxTUwJy0',
    appId: '1:245885129906:ios:a795e5e609f982678b65ab',
    messagingSenderId: '245885129906',
    projectId: 'saadp-88043',
    storageBucket: 'saadp-88043.firebasestorage.app',
    iosBundleId: 'com.example.projectgrad',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpzx4ZSIq_Hhz9EnmO-WUGRUPnRGGIohY',
    appId: '1:245885129906:web:4e559c17a8b236558b65ab',
    messagingSenderId: '245885129906',
    projectId: 'saadp-88043',
    authDomain: 'saadp-88043.firebaseapp.com',
    storageBucket: 'saadp-88043.firebasestorage.app',
    measurementId: 'G-TEBMDK3N6B',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqhCjlpYaozaD-1vCo8mzrSHsqxTUwJy0',
    appId: '1:245885129906:ios:a795e5e609f982678b65ab',
    messagingSenderId: '245885129906',
    projectId: 'saadp-88043',
    storageBucket: 'saadp-88043.firebasestorage.app',
    iosBundleId: 'com.example.projectgrad',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpzx4ZSIq_Hhz9EnmO-WUGRUPnRGGIohY',
    appId: '1:245885129906:web:ea6b7784329acbd28b65ab',
    messagingSenderId: '245885129906',
    projectId: 'saadp-88043',
    authDomain: 'saadp-88043.firebaseapp.com',
    storageBucket: 'saadp-88043.firebasestorage.app',
    measurementId: 'G-ZXMY2DXZJ7',
  );

}